#lang sicp

(define (make-monitored f)
  (let ((call-count 0))
    (define (mf x)
      (set! call-count (+ call-count 1))
      (f x))
    (define (dispatch x)
      (cond ((eq? x 'how-many-calls?)
             call-count)
            ((eq? x 'reset-count)
             (set! call-count 0)
             (values))
            (else (mf x))))
    dispatch))

(define s (make-monitored sqrt))

(display "Make three calls to monitored sqrt...\n")
(display "Call ")
(display (s 'how-many-calls?))
(display " => ")
(display (s 100))
(newline)
(display "Call ")
(display (s 'how-many-calls?))
(display " => ")
(display (s 100))
(newline)
(display "Call ")
(display (s 'how-many-calls?))
(display " => ")
(display (s 100))
(newline)
(display "How many calls total? ")
(display (s 'how-many-calls?))
(newline)
